/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RecordId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Genre = IDL.Text;
export const AudioTrack = IDL.Record({
  'id' : RecordId,
  'bpm' : IDL.Nat,
  'title' : IDL.Text,
  'isPremium' : IDL.Bool,
  'audioBlob' : ExternalBlob,
  'moodTags' : IDL.Vec(IDL.Text),
  'genre' : Genre,
  'durationSeconds' : IDL.Nat,
  'artist' : IDL.Text,
});
export const VoiceEmotion = IDL.Variant({
  'sad' : IDL.Null,
  'happy' : IDL.Null,
  'energetic' : IDL.Null,
  'excited' : IDL.Null,
  'neutral' : IDL.Null,
});
export const VideoTone = IDL.Variant({
  'humorous' : IDL.Null,
  'viral' : IDL.Null,
  'cinematic' : IDL.Null,
  'educational' : IDL.Null,
  'motivational' : IDL.Null,
});
export const BulkJobStyle = IDL.Variant({
  'bold' : IDL.Null,
  'trendy' : IDL.Null,
  'minimal' : IDL.Null,
  'cinematic' : IDL.Null,
  'educational' : IDL.Null,
});
export const VideoAspectRatio = IDL.Variant({
  'shorts9x16' : IDL.Null,
  'landscape16x9' : IDL.Null,
});
export const BulkJobInput = IDL.Record({
  'voiceType' : IDL.Text,
  'videoCount' : IDL.Nat,
  'voiceEmotion' : VoiceEmotion,
  'tone' : VideoTone,
  'language' : IDL.Text,
  'style' : BulkJobStyle,
  'durationSeconds' : IDL.Nat,
  'prompt' : IDL.Text,
  'aspectRatio' : VideoAspectRatio,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const EffectCategory = IDL.Variant({
  '_3d' : IDL.Null,
  'lut' : IDL.Null,
  'cinematic' : IDL.Null,
  'transition' : IDL.Null,
  'filter' : IDL.Null,
  'glitch' : IDL.Null,
});
export const Effect = IDL.Record({
  'id' : RecordId,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'category' : EffectCategory,
  'previewBlob' : ExternalBlob,
});
export const PostStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'published' : IDL.Null,
  'failed' : IDL.Null,
});
export const Platform = IDL.Variant({
  'tiktok' : IDL.Null,
  'twitter' : IDL.Null,
  'instagram' : IDL.Null,
  'youtube' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : RecordId,
  'status' : PostStatus,
  'hashtags' : IDL.Vec(IDL.Text),
  'scheduledTime' : IDL.Int,
  'userId' : IDL.Principal,
  'platform' : Platform,
  'projectId' : RecordId,
  'caption' : IDL.Text,
});
export const ProjectStatus = IDL.Variant({
  'processing' : IDL.Null,
  'draft' : IDL.Null,
  'ready' : IDL.Null,
});
export const Resolution = IDL.Variant({
  '_2k' : IDL.Null,
  '_4k' : IDL.Null,
  '_1080p' : IDL.Null,
  '_720p' : IDL.Null,
});
export const ProjectInput = IDL.Record({
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'resolution' : Resolution,
  'thumbnailBlob' : ExternalBlob,
  'durationSeconds' : IDL.Nat,
  'timelineStateJson' : IDL.Text,
});
export const TemplateCategory = IDL.Variant({
  'tiktok' : IDL.Null,
  'shorts' : IDL.Null,
  'youtube' : IDL.Null,
  'reels' : IDL.Null,
});
export const VideoTemplate = IDL.Record({
  'id' : RecordId,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'usageCount' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'category' : TemplateCategory,
  'previewBlob' : ExternalBlob,
});
export const VideoProject = IDL.Record({
  'id' : RecordId,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'resolution' : Resolution,
  'thumbnailBlob' : ExternalBlob,
  'durationSeconds' : IDL.Nat,
  'timestamp' : IDL.Int,
  'timelineStateJson' : IDL.Text,
});
export const BulkJobStatus = IDL.Variant({
  'done' : IDL.Null,
  'queued' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const BulkJob = IDL.Record({
  'id' : RecordId,
  'status' : BulkJobStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'voiceType' : IDL.Text,
  'videoCount' : IDL.Nat,
  'voiceEmotion' : VoiceEmotion,
  'completedVideos' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'tone' : VideoTone,
  'language' : IDL.Text,
  'style' : BulkJobStyle,
  'durationSeconds' : IDL.Nat,
  'prompt' : IDL.Text,
  'totalScripts' : IDL.Nat,
  'aspectRatio' : VideoAspectRatio,
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'aiUsageCount' : IDL.Nat,
  'displayName' : IDL.Text,
  'avatarBlob' : ExternalBlob,
  'tier' : SubscriptionTier,
  'createdTime' : IDL.Int,
  'youtubeId' : IDL.Opt(IDL.Text),
  'twitterId' : IDL.Opt(IDL.Text),
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'instagramId' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ProjectStats = IDL.Record({
  'platformBreakdown' : IDL.Vec(IDL.Tuple(Platform, IDL.Nat)),
  'shareCount' : IDL.Nat,
  'viewCount' : IDL.Nat,
  'projectId' : RecordId,
  'exportCount' : IDL.Nat,
});
export const GeneratedScript = IDL.Record({
  'id' : RecordId,
  'cta' : IDL.Text,
  'title' : IDL.Text,
  'viralityScore' : IDL.Nat,
  'hashtags' : IDL.Vec(IDL.Text),
  'scenes' : IDL.Vec(IDL.Text),
  'body' : IDL.Text,
  'hook' : IDL.Text,
  'jobId' : RecordId,
  'description' : IDL.Text,
});
export const GeneratedVideo = IDL.Record({
  'id' : RecordId,
  'status' : BulkJobStatus,
  'scriptId' : RecordId,
  'jobId' : RecordId,
  'thumbnailBlob' : ExternalBlob,
  'durationSeconds' : IDL.Nat,
  'aspectRatio' : VideoAspectRatio,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const AiFeature = IDL.Variant({
  'beatSync' : IDL.Null,
  'bgRemover' : IDL.Null,
  'voiceGen' : IDL.Null,
  'textToVideo' : IDL.Null,
  'faceTracking' : IDL.Null,
  'autoCaptions' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyEffect' : IDL.Func([IDL.Nat, RecordId], [], []),
  'applyTemplate' : IDL.Func([IDL.Nat, RecordId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'configureStripe' : IDL.Func([StripeConfiguration], [], []),
  'createAudioTrack' : IDL.Func([AudioTrack], [IDL.Nat], []),
  'createBulkJob' : IDL.Func([BulkJobInput], [RecordId], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createEffect' : IDL.Func([Effect], [IDL.Nat], []),
  'createPost' : IDL.Func([Post], [IDL.Nat], []),
  'createProject' : IDL.Func([ProjectInput], [RecordId], []),
  'createTemplate' : IDL.Func([VideoTemplate], [IDL.Nat], []),
  'deleteAudioTrack' : IDL.Func([IDL.Nat], [], []),
  'deleteBulkJob' : IDL.Func([RecordId], [], []),
  'deleteEffect' : IDL.Func([IDL.Nat], [], []),
  'deleteGeneratedScript' : IDL.Func([RecordId], [], []),
  'deleteGeneratedVideo' : IDL.Func([RecordId], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'deleteTemplate' : IDL.Func([IDL.Nat], [], []),
  'deleteUserProject' : IDL.Func([RecordId], [], []),
  'downgradeToFree' : IDL.Func([], [], []),
  'filterPostsByStatus' : IDL.Func(
      [IDL.Vec(Post), PostStatus],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'filterProjectsByStatus' : IDL.Func(
      [IDL.Vec(VideoProject), ProjectStatus],
      [IDL.Vec(VideoProject)],
      ['query'],
    ),
  'filterTracksByGenre' : IDL.Func(
      [IDL.Vec(AudioTrack), Genre],
      [IDL.Vec(AudioTrack)],
      ['query'],
    ),
  'getBulkJob' : IDL.Func([RecordId], [BulkJob], ['query']),
  'getBulkJobsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BulkJob)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckoutSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getEffect' : IDL.Func([IDL.Nat], [Effect], ['query']),
  'getEffectCategories' : IDL.Func([], [IDL.Vec(EffectCategory)], ['query']),
  'getFreeTierSummary' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'aiUsageLimit' : IDL.Nat,
          'isFree' : IDL.Bool,
          'remainingAiUses' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPostInternal' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getProject' : IDL.Func([RecordId], [VideoProject], ['query']),
  'getProjectStats' : IDL.Func([IDL.Nat], [ProjectStats], ['query']),
  'getProjectsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoProject)],
      ['query'],
    ),
  'getScriptsForJob' : IDL.Func(
      [RecordId],
      [IDL.Vec(GeneratedScript)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTemplate' : IDL.Func([IDL.Nat], [VideoTemplate], ['query']),
  'getTemplatesByUsageCount' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(VideoTemplate)],
      ['query'],
    ),
  'getTrack' : IDL.Func([IDL.Nat], [AudioTrack], ['query']),
  'getTracksGroupedByGenre' : IDL.Func(
      [IDL.Vec(AudioTrack)],
      [IDL.Vec(IDL.Tuple(Genre, IDL.Vec(AudioTrack)))],
      ['query'],
    ),
  'getUpcomingPostsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideosForJob' : IDL.Func(
      [RecordId],
      [IDL.Vec(GeneratedVideo)],
      ['query'],
    ),
  'incrementExportCount' : IDL.Func([IDL.Nat], [], []),
  'incrementProjectPostViewCount' : IDL.Func([IDL.Nat], [], []),
  'incrementShareCount' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFreeTier' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isPremiumTrack' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGeneratedScript' : IDL.Func([GeneratedScript], [RecordId], []),
  'saveGeneratedVideo' : IDL.Func([GeneratedVideo], [RecordId], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'sortEffectsByName' : IDL.Func(
      [IDL.Vec(Effect)],
      [IDL.Vec(Effect)],
      ['query'],
    ),
  'sortPostsByScheduledTime' : IDL.Func(
      [IDL.Vec(Post)],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'sortProjectsByTimestamp' : IDL.Func(
      [IDL.Vec(VideoProject)],
      [IDL.Vec(VideoProject)],
      ['query'],
    ),
  'toShoppingItemArray' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat))],
      [IDL.Vec(ShoppingItem)],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBulkJobStatus' : IDL.Func(
      [RecordId, BulkJobStatus, IDL.Nat, IDL.Opt(IDL.Int)],
      [],
      [],
    ),
  'updatePost' : IDL.Func([IDL.Nat, Post], [], []),
  'updateProject' : IDL.Func([RecordId, VideoProject], [], []),
  'upgradeToPro' : IDL.Func([IDL.Text], [], []),
  'useAiFeature' : IDL.Func([AiFeature], [], []),
  'useAudioTrack' : IDL.Func([IDL.Nat, RecordId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RecordId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Genre = IDL.Text;
  const AudioTrack = IDL.Record({
    'id' : RecordId,
    'bpm' : IDL.Nat,
    'title' : IDL.Text,
    'isPremium' : IDL.Bool,
    'audioBlob' : ExternalBlob,
    'moodTags' : IDL.Vec(IDL.Text),
    'genre' : Genre,
    'durationSeconds' : IDL.Nat,
    'artist' : IDL.Text,
  });
  const VoiceEmotion = IDL.Variant({
    'sad' : IDL.Null,
    'happy' : IDL.Null,
    'energetic' : IDL.Null,
    'excited' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const VideoTone = IDL.Variant({
    'humorous' : IDL.Null,
    'viral' : IDL.Null,
    'cinematic' : IDL.Null,
    'educational' : IDL.Null,
    'motivational' : IDL.Null,
  });
  const BulkJobStyle = IDL.Variant({
    'bold' : IDL.Null,
    'trendy' : IDL.Null,
    'minimal' : IDL.Null,
    'cinematic' : IDL.Null,
    'educational' : IDL.Null,
  });
  const VideoAspectRatio = IDL.Variant({
    'shorts9x16' : IDL.Null,
    'landscape16x9' : IDL.Null,
  });
  const BulkJobInput = IDL.Record({
    'voiceType' : IDL.Text,
    'videoCount' : IDL.Nat,
    'voiceEmotion' : VoiceEmotion,
    'tone' : VideoTone,
    'language' : IDL.Text,
    'style' : BulkJobStyle,
    'durationSeconds' : IDL.Nat,
    'prompt' : IDL.Text,
    'aspectRatio' : VideoAspectRatio,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const EffectCategory = IDL.Variant({
    '_3d' : IDL.Null,
    'lut' : IDL.Null,
    'cinematic' : IDL.Null,
    'transition' : IDL.Null,
    'filter' : IDL.Null,
    'glitch' : IDL.Null,
  });
  const Effect = IDL.Record({
    'id' : RecordId,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'category' : EffectCategory,
    'previewBlob' : ExternalBlob,
  });
  const PostStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'published' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Platform = IDL.Variant({
    'tiktok' : IDL.Null,
    'twitter' : IDL.Null,
    'instagram' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const Post = IDL.Record({
    'id' : RecordId,
    'status' : PostStatus,
    'hashtags' : IDL.Vec(IDL.Text),
    'scheduledTime' : IDL.Int,
    'userId' : IDL.Principal,
    'platform' : Platform,
    'projectId' : RecordId,
    'caption' : IDL.Text,
  });
  const ProjectStatus = IDL.Variant({
    'processing' : IDL.Null,
    'draft' : IDL.Null,
    'ready' : IDL.Null,
  });
  const Resolution = IDL.Variant({
    '_2k' : IDL.Null,
    '_4k' : IDL.Null,
    '_1080p' : IDL.Null,
    '_720p' : IDL.Null,
  });
  const ProjectInput = IDL.Record({
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'resolution' : Resolution,
    'thumbnailBlob' : ExternalBlob,
    'durationSeconds' : IDL.Nat,
    'timelineStateJson' : IDL.Text,
  });
  const TemplateCategory = IDL.Variant({
    'tiktok' : IDL.Null,
    'shorts' : IDL.Null,
    'youtube' : IDL.Null,
    'reels' : IDL.Null,
  });
  const VideoTemplate = IDL.Record({
    'id' : RecordId,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'usageCount' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'category' : TemplateCategory,
    'previewBlob' : ExternalBlob,
  });
  const VideoProject = IDL.Record({
    'id' : RecordId,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'resolution' : Resolution,
    'thumbnailBlob' : ExternalBlob,
    'durationSeconds' : IDL.Nat,
    'timestamp' : IDL.Int,
    'timelineStateJson' : IDL.Text,
  });
  const BulkJobStatus = IDL.Variant({
    'done' : IDL.Null,
    'queued' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const BulkJob = IDL.Record({
    'id' : RecordId,
    'status' : BulkJobStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'voiceType' : IDL.Text,
    'videoCount' : IDL.Nat,
    'voiceEmotion' : VoiceEmotion,
    'completedVideos' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'tone' : VideoTone,
    'language' : IDL.Text,
    'style' : BulkJobStyle,
    'durationSeconds' : IDL.Nat,
    'prompt' : IDL.Text,
    'totalScripts' : IDL.Nat,
    'aspectRatio' : VideoAspectRatio,
  });
  const SubscriptionTier = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
  const UserProfile = IDL.Record({
    'aiUsageCount' : IDL.Nat,
    'displayName' : IDL.Text,
    'avatarBlob' : ExternalBlob,
    'tier' : SubscriptionTier,
    'createdTime' : IDL.Int,
    'youtubeId' : IDL.Opt(IDL.Text),
    'twitterId' : IDL.Opt(IDL.Text),
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'instagramId' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ProjectStats = IDL.Record({
    'platformBreakdown' : IDL.Vec(IDL.Tuple(Platform, IDL.Nat)),
    'shareCount' : IDL.Nat,
    'viewCount' : IDL.Nat,
    'projectId' : RecordId,
    'exportCount' : IDL.Nat,
  });
  const GeneratedScript = IDL.Record({
    'id' : RecordId,
    'cta' : IDL.Text,
    'title' : IDL.Text,
    'viralityScore' : IDL.Nat,
    'hashtags' : IDL.Vec(IDL.Text),
    'scenes' : IDL.Vec(IDL.Text),
    'body' : IDL.Text,
    'hook' : IDL.Text,
    'jobId' : RecordId,
    'description' : IDL.Text,
  });
  const GeneratedVideo = IDL.Record({
    'id' : RecordId,
    'status' : BulkJobStatus,
    'scriptId' : RecordId,
    'jobId' : RecordId,
    'thumbnailBlob' : ExternalBlob,
    'durationSeconds' : IDL.Nat,
    'aspectRatio' : VideoAspectRatio,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const AiFeature = IDL.Variant({
    'beatSync' : IDL.Null,
    'bgRemover' : IDL.Null,
    'voiceGen' : IDL.Null,
    'textToVideo' : IDL.Null,
    'faceTracking' : IDL.Null,
    'autoCaptions' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyEffect' : IDL.Func([IDL.Nat, RecordId], [], []),
    'applyTemplate' : IDL.Func([IDL.Nat, RecordId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'configureStripe' : IDL.Func([StripeConfiguration], [], []),
    'createAudioTrack' : IDL.Func([AudioTrack], [IDL.Nat], []),
    'createBulkJob' : IDL.Func([BulkJobInput], [RecordId], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createEffect' : IDL.Func([Effect], [IDL.Nat], []),
    'createPost' : IDL.Func([Post], [IDL.Nat], []),
    'createProject' : IDL.Func([ProjectInput], [RecordId], []),
    'createTemplate' : IDL.Func([VideoTemplate], [IDL.Nat], []),
    'deleteAudioTrack' : IDL.Func([IDL.Nat], [], []),
    'deleteBulkJob' : IDL.Func([RecordId], [], []),
    'deleteEffect' : IDL.Func([IDL.Nat], [], []),
    'deleteGeneratedScript' : IDL.Func([RecordId], [], []),
    'deleteGeneratedVideo' : IDL.Func([RecordId], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'deleteTemplate' : IDL.Func([IDL.Nat], [], []),
    'deleteUserProject' : IDL.Func([RecordId], [], []),
    'downgradeToFree' : IDL.Func([], [], []),
    'filterPostsByStatus' : IDL.Func(
        [IDL.Vec(Post), PostStatus],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'filterProjectsByStatus' : IDL.Func(
        [IDL.Vec(VideoProject), ProjectStatus],
        [IDL.Vec(VideoProject)],
        ['query'],
      ),
    'filterTracksByGenre' : IDL.Func(
        [IDL.Vec(AudioTrack), Genre],
        [IDL.Vec(AudioTrack)],
        ['query'],
      ),
    'getBulkJob' : IDL.Func([RecordId], [BulkJob], ['query']),
    'getBulkJobsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BulkJob)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckoutSessionStatus' : IDL.Func(
        [IDL.Text],
        [StripeSessionStatus],
        [],
      ),
    'getEffect' : IDL.Func([IDL.Nat], [Effect], ['query']),
    'getEffectCategories' : IDL.Func([], [IDL.Vec(EffectCategory)], ['query']),
    'getFreeTierSummary' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'aiUsageLimit' : IDL.Nat,
            'isFree' : IDL.Bool,
            'remainingAiUses' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPostInternal' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getProject' : IDL.Func([RecordId], [VideoProject], ['query']),
    'getProjectStats' : IDL.Func([IDL.Nat], [ProjectStats], ['query']),
    'getProjectsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoProject)],
        ['query'],
      ),
    'getScriptsForJob' : IDL.Func(
        [RecordId],
        [IDL.Vec(GeneratedScript)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTemplate' : IDL.Func([IDL.Nat], [VideoTemplate], ['query']),
    'getTemplatesByUsageCount' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(VideoTemplate)],
        ['query'],
      ),
    'getTrack' : IDL.Func([IDL.Nat], [AudioTrack], ['query']),
    'getTracksGroupedByGenre' : IDL.Func(
        [IDL.Vec(AudioTrack)],
        [IDL.Vec(IDL.Tuple(Genre, IDL.Vec(AudioTrack)))],
        ['query'],
      ),
    'getUpcomingPostsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideosForJob' : IDL.Func(
        [RecordId],
        [IDL.Vec(GeneratedVideo)],
        ['query'],
      ),
    'incrementExportCount' : IDL.Func([IDL.Nat], [], []),
    'incrementProjectPostViewCount' : IDL.Func([IDL.Nat], [], []),
    'incrementShareCount' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFreeTier' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isPremiumTrack' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGeneratedScript' : IDL.Func([GeneratedScript], [RecordId], []),
    'saveGeneratedVideo' : IDL.Func([GeneratedVideo], [RecordId], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'sortEffectsByName' : IDL.Func(
        [IDL.Vec(Effect)],
        [IDL.Vec(Effect)],
        ['query'],
      ),
    'sortPostsByScheduledTime' : IDL.Func(
        [IDL.Vec(Post)],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'sortProjectsByTimestamp' : IDL.Func(
        [IDL.Vec(VideoProject)],
        [IDL.Vec(VideoProject)],
        ['query'],
      ),
    'toShoppingItemArray' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat))],
        [IDL.Vec(ShoppingItem)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBulkJobStatus' : IDL.Func(
        [RecordId, BulkJobStatus, IDL.Nat, IDL.Opt(IDL.Int)],
        [],
        [],
      ),
    'updatePost' : IDL.Func([IDL.Nat, Post], [], []),
    'updateProject' : IDL.Func([RecordId, VideoProject], [], []),
    'upgradeToPro' : IDL.Func([IDL.Text], [], []),
    'useAiFeature' : IDL.Func([AiFeature], [], []),
    'useAudioTrack' : IDL.Func([IDL.Nat, RecordId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };