/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AiFeature = { 'beatSync' : null } |
  { 'bgRemover' : null } |
  { 'voiceGen' : null } |
  { 'textToVideo' : null } |
  { 'faceTracking' : null } |
  { 'autoCaptions' : null };
export interface AudioTrack {
  'id' : RecordId,
  'bpm' : bigint,
  'title' : string,
  'isPremium' : boolean,
  'audioBlob' : ExternalBlob,
  'moodTags' : Array<string>,
  'genre' : Genre,
  'durationSeconds' : bigint,
  'artist' : string,
}
export interface BulkJob {
  'id' : RecordId,
  'status' : BulkJobStatus,
  'completedAt' : [] | [bigint],
  'voiceType' : string,
  'videoCount' : bigint,
  'voiceEmotion' : VoiceEmotion,
  'completedVideos' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'tone' : VideoTone,
  'language' : string,
  'style' : BulkJobStyle,
  'durationSeconds' : bigint,
  'prompt' : string,
  'totalScripts' : bigint,
  'aspectRatio' : VideoAspectRatio,
}
export interface BulkJobInput {
  'voiceType' : string,
  'videoCount' : bigint,
  'voiceEmotion' : VoiceEmotion,
  'tone' : VideoTone,
  'language' : string,
  'style' : BulkJobStyle,
  'durationSeconds' : bigint,
  'prompt' : string,
  'aspectRatio' : VideoAspectRatio,
}
export type BulkJobStatus = { 'done' : null } |
  { 'queued' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type BulkJobStyle = { 'bold' : null } |
  { 'trendy' : null } |
  { 'minimal' : null } |
  { 'cinematic' : null } |
  { 'educational' : null };
export interface Effect {
  'id' : RecordId,
  'isPremium' : boolean,
  'name' : string,
  'category' : EffectCategory,
  'previewBlob' : ExternalBlob,
}
export type EffectCategory = { '_3d' : null } |
  { 'lut' : null } |
  { 'cinematic' : null } |
  { 'transition' : null } |
  { 'filter' : null } |
  { 'glitch' : null };
export type ExternalBlob = Uint8Array;
export interface GeneratedScript {
  'id' : RecordId,
  'cta' : string,
  'title' : string,
  'viralityScore' : bigint,
  'hashtags' : Array<string>,
  'scenes' : Array<string>,
  'body' : string,
  'hook' : string,
  'jobId' : RecordId,
  'description' : string,
}
export interface GeneratedVideo {
  'id' : RecordId,
  'status' : BulkJobStatus,
  'scriptId' : RecordId,
  'jobId' : RecordId,
  'thumbnailBlob' : ExternalBlob,
  'durationSeconds' : bigint,
  'aspectRatio' : VideoAspectRatio,
}
export type Genre = string;
export type Platform = { 'tiktok' : null } |
  { 'twitter' : null } |
  { 'instagram' : null } |
  { 'youtube' : null };
export interface Post {
  'id' : RecordId,
  'status' : PostStatus,
  'hashtags' : Array<string>,
  'scheduledTime' : bigint,
  'userId' : Principal,
  'platform' : Platform,
  'projectId' : RecordId,
  'caption' : string,
}
export type PostStatus = { 'scheduled' : null } |
  { 'published' : null } |
  { 'failed' : null };
export interface ProjectInput {
  'status' : ProjectStatus,
  'title' : string,
  'description' : string,
  'resolution' : Resolution,
  'thumbnailBlob' : ExternalBlob,
  'durationSeconds' : bigint,
  'timelineStateJson' : string,
}
export interface ProjectStats {
  'platformBreakdown' : Array<[Platform, bigint]>,
  'shareCount' : bigint,
  'viewCount' : bigint,
  'projectId' : RecordId,
  'exportCount' : bigint,
}
export type ProjectStatus = { 'processing' : null } |
  { 'draft' : null } |
  { 'ready' : null };
export type RecordId = bigint;
export type Resolution = { '_2k' : null } |
  { '_4k' : null } |
  { '_1080p' : null } |
  { '_720p' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionTier = { 'pro' : null } |
  { 'free' : null };
export type TemplateCategory = { 'tiktok' : null } |
  { 'shorts' : null } |
  { 'youtube' : null } |
  { 'reels' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'aiUsageCount' : bigint,
  'displayName' : string,
  'avatarBlob' : ExternalBlob,
  'tier' : SubscriptionTier,
  'createdTime' : bigint,
  'youtubeId' : [] | [string],
  'twitterId' : [] | [string],
  'stripePaymentIntentId' : [] | [string],
  'instagramId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VideoAspectRatio = { 'shorts9x16' : null } |
  { 'landscape16x9' : null };
export interface VideoProject {
  'id' : RecordId,
  'status' : ProjectStatus,
  'title' : string,
  'userId' : Principal,
  'description' : string,
  'resolution' : Resolution,
  'thumbnailBlob' : ExternalBlob,
  'durationSeconds' : bigint,
  'timestamp' : bigint,
  'timelineStateJson' : string,
}
export interface VideoTemplate {
  'id' : RecordId,
  'isPremium' : boolean,
  'name' : string,
  'usageCount' : bigint,
  'tags' : Array<string>,
  'category' : TemplateCategory,
  'previewBlob' : ExternalBlob,
}
export type VideoTone = { 'humorous' : null } |
  { 'viral' : null } |
  { 'cinematic' : null } |
  { 'educational' : null } |
  { 'motivational' : null };
export type VoiceEmotion = { 'sad' : null } |
  { 'happy' : null } |
  { 'energetic' : null } |
  { 'excited' : null } |
  { 'neutral' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyEffect' : ActorMethod<[bigint, RecordId], undefined>,
  'applyTemplate' : ActorMethod<[bigint, RecordId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'configureStripe' : ActorMethod<[StripeConfiguration], undefined>,
  'createAudioTrack' : ActorMethod<[AudioTrack], bigint>,
  'createBulkJob' : ActorMethod<[BulkJobInput], RecordId>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createEffect' : ActorMethod<[Effect], bigint>,
  'createPost' : ActorMethod<[Post], bigint>,
  'createProject' : ActorMethod<[ProjectInput], RecordId>,
  'createTemplate' : ActorMethod<[VideoTemplate], bigint>,
  'deleteAudioTrack' : ActorMethod<[bigint], undefined>,
  'deleteBulkJob' : ActorMethod<[RecordId], undefined>,
  'deleteEffect' : ActorMethod<[bigint], undefined>,
  'deleteGeneratedScript' : ActorMethod<[RecordId], undefined>,
  'deleteGeneratedVideo' : ActorMethod<[RecordId], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'deleteTemplate' : ActorMethod<[bigint], undefined>,
  'deleteUserProject' : ActorMethod<[RecordId], undefined>,
  'downgradeToFree' : ActorMethod<[], undefined>,
  'filterPostsByStatus' : ActorMethod<[Array<Post>, PostStatus], Array<Post>>,
  'filterProjectsByStatus' : ActorMethod<
    [Array<VideoProject>, ProjectStatus],
    Array<VideoProject>
  >,
  'filterTracksByGenre' : ActorMethod<
    [Array<AudioTrack>, Genre],
    Array<AudioTrack>
  >,
  'getBulkJob' : ActorMethod<[RecordId], BulkJob>,
  'getBulkJobsByUser' : ActorMethod<[Principal], Array<BulkJob>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckoutSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getEffect' : ActorMethod<[bigint], Effect>,
  'getEffectCategories' : ActorMethod<[], Array<EffectCategory>>,
  'getFreeTierSummary' : ActorMethod<
    [Principal],
    { 'aiUsageLimit' : bigint, 'isFree' : boolean, 'remainingAiUses' : bigint }
  >,
  'getPostInternal' : ActorMethod<[bigint], Post>,
  'getProject' : ActorMethod<[RecordId], VideoProject>,
  'getProjectStats' : ActorMethod<[bigint], ProjectStats>,
  'getProjectsByUser' : ActorMethod<[Principal], Array<VideoProject>>,
  'getScriptsForJob' : ActorMethod<[RecordId], Array<GeneratedScript>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTemplate' : ActorMethod<[bigint], VideoTemplate>,
  'getTemplatesByUsageCount' : ActorMethod<
    [[] | [bigint]],
    Array<VideoTemplate>
  >,
  'getTrack' : ActorMethod<[bigint], AudioTrack>,
  'getTracksGroupedByGenre' : ActorMethod<
    [Array<AudioTrack>],
    Array<[Genre, Array<AudioTrack>]>
  >,
  'getUpcomingPostsForUser' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideosForJob' : ActorMethod<[RecordId], Array<GeneratedVideo>>,
  'incrementExportCount' : ActorMethod<[bigint], undefined>,
  'incrementProjectPostViewCount' : ActorMethod<[bigint], undefined>,
  'incrementShareCount' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFreeTier' : ActorMethod<[Principal], boolean>,
  'isPremiumTrack' : ActorMethod<[bigint], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGeneratedScript' : ActorMethod<[GeneratedScript], RecordId>,
  'saveGeneratedVideo' : ActorMethod<[GeneratedVideo], RecordId>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'sortEffectsByName' : ActorMethod<[Array<Effect>], Array<Effect>>,
  'sortPostsByScheduledTime' : ActorMethod<[Array<Post>], Array<Post>>,
  'sortProjectsByTimestamp' : ActorMethod<
    [Array<VideoProject>],
    Array<VideoProject>
  >,
  'toShoppingItemArray' : ActorMethod<
    [Array<[string, string, bigint]>],
    Array<ShoppingItem>
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBulkJobStatus' : ActorMethod<
    [RecordId, BulkJobStatus, bigint, [] | [bigint]],
    undefined
  >,
  'updatePost' : ActorMethod<[bigint, Post], undefined>,
  'updateProject' : ActorMethod<[RecordId, VideoProject], undefined>,
  'upgradeToPro' : ActorMethod<[string], undefined>,
  'useAiFeature' : ActorMethod<[AiFeature], undefined>,
  'useAudioTrack' : ActorMethod<[bigint, RecordId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];